### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#235]
* [x] Bump version in `setup.py` to 0.6
* [x] Update changelog release date for 0.6
* [x] Push to PYPI
