### ISSUE TITLE
Release Ariadne 0.13

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#479]
# TODO

- [x] Update dependencies
- [x] Fix linters errors on repo
- [x] #483 
- [x] Update changelog
- [x] Write [release notes](https://github.com/mirumee/ariadne-website/pull/75)
- [x] Reach to our amazing art team for tweet graphics
