### ISSUE TITLE
Release Ariadne 0.16

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#906]
# TODO

- [x] Verify docs are up to date
- [x] Verify changelog is up to date
- [x] Write release announcement

**Comment by rafalp** [comment]
Note that I'll be out of office for next two weeks. But I'll work on 0.16 release when I'm back.

If you **really** need to use 0.16, I've made 0.16.0b1 pre-release that you can install by pinning your dependencies at `ariadne==0.16.0b1`.

Cheers!
